### ISSUE TITLE
Does not work on Cheap Cast !!

### ISSUE THREAD

**Issue by maheshprabhu** [LeonNicholls/DIAL#1]
As i dint have Chrome cast device , i tried your application on Cheap Cast  ( emulates the Chrome Cast Dongle ) which is available on PlayStore. But your app failed to even discover the chrome cast server . Any idea??

**Comment by LeonNicholls** [comment]
I checked in a small change; see if that works for you.

**Comment by maheshprabhu** [comment]
Thanks for the quick reply.. Works like charm now!! .. Is there any way to control the 1st screen playback like pause seek etc.. ?? i could see in your code that it can be done through the Websocket.. Could you please help me out in this?? Sample commands for youtube app would help..

**Comment by LeonNicholls** [comment]
Media playback is controlled with the RAMP protocol. The RAMP protocol is documented here: https://github.com/entertailion/Fling

**Comment by maheshprabhu** [comment]
Thank you!!.. I will try out on this.. Other than YouTube playback.. With your DIAL Client is there a way to play external video links other than youtube by registering GoogleCastPlayer or similar..?

**Comment by LeonNicholls** [comment]
The only way to play non-YouTube videos is to have a app id from Google for
a whitelisted ChromeCast device.

**Comment by maheshprabhu** [comment]
I will try that out.. Thanks for your help!!
